spring.application.name=securitydemo

spring.security.user.password=demo@123
spring.security.user.name=admin


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test-db


spring.app.jwtSecret=mysecretKey0203046296790017saadadasasaaaaaaaaaaaaaaadddddddddd
spring.app.jwtExpirationMs = 300000